modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPLv3"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
#updateJSONURL="${mod_updates}"
authors="${mod_authors}"
#credits="${mod_credits}"
#logoFile="${mod_logo}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
versionRange="${forge_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
versionRange="${mc_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
