modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="propertymodifier"
version="${file.jarVersion}"
displayName="Property Modifier"
displayURL="http://www.curseforge.com/minecraft/mc-mods/property-modifier"
authors="IchHabeHunger54"
description='''
Allows tweaking various properties of blocks and items. Also adds some other tweaks to aid with that, such as the ability to create new creative tabs or add composter inputs.
'''
[[dependencies.propertymodifier]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.propertymodifier]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
